platform :ios, '8.0'

target 'Sample' do
  use_frameworks!

  # Pods for Sample
  pod 'PhoneNumberKit', :path => '../..'
  pod 'CommonKit', git: 'https://github.com/oskarirauta/CommonKit.git'

  target 'SampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
